<section class = "container-annoncement">
    <table>
        <tbody>
            <?php foreach($users as $user):?>
            <tr>
                <td><a href="index.php?action=admins.admin.user&id=<?=$user->getId()?>"> <?=$user->getName() .' '. $user->getFirstName()?></a></td>
                <td><?=$user->getDateAt() ?></td>
                <td>
                    <form action="index.php?action=user" method="post">
                        <input type="hidden" name="id" value="<?=$user->getId()?>">
                        <button style="background: transparent; border:none;" type="submit" name="edit"><i class="fa-solid fa-gear"></i></button>
                    </form>
                    <form action="index.php?action=user" method="post">
                        <input type="hidden" name="id" value="<?=$user->getId()?>">
                        <button style="background: transparent; border:none;" type="submit" name="ban"><i class="fa-solid fa-trash-can"></i></button>
                    </form>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>
<div class = "pagination">
    <?php if($currentPage > 1):?>
        <a href="index.php?action=<?=$_GET['action']?>&p=<?=$currentPage - 1?>">&laquo; Page précédent</a>
    <?php endif;?>
    <?php for($i= 1; $i <= $pages; $i++):?>
        <a  <?=($i == $currentPage)?'id="active"':''?>" href="index.php?action=<?=$_GET['action']?>&pages=<?=$i?>"><?=$i?></a>
    <?php endfor;?>
    <?php if($currentPage < $pages):?>
        <a href="index.php?action=<?=$_GET['action']?>&p=<?=$currentPage + 1?>"> Page suivante &raquo</a>
    <?php endif ?>
</div>