<?php
    use App\App;
?>
<section class = "container-annoncement">
    <table>
        <tbody>
            <?php foreach($users as $user):?>
            <tr>
                <td><a href="<?=\App\App::getInstance()->routes->url('Admins.Admin.user', ['id' => $user->getid()])?>"> <?=$user->getName() .' '. $user->getFirstName()?></a></td>
                <td><?=$user->getDateAt() ?></td>
                <td>
                    <!-- ajouter voir user et suprime user -->

                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</section>
<div class = "pagination">
    <?php if($currentPage > 1):?>
        <a href="<?=App::getInstance()->routes->url('Admins.Admin.users')?>&p=<?=$currentPage - 1?>">&laquo; Page précédent</a>
    <?php endif;?>
    <?php for($i= 1; $i <= $pages; $i++):?>
        <a  <?=($i == $currentPage)?'id="active"':''?> href="<?=App::getInstance()->routes->url('Admins.Admin.users')?>&p=<?=$i?>"><?=$i?></a>
    <?php endfor;?>
    <?php if($currentPage < $pages):?>
        <a href="<?=App::getInstance()->routes->url('Admins.Admin.users')?>&p=<?=$currentPage + 1?>"> Page suivante &raquo</a>
    <?php endif ?>
</div>