<?php use App\App;?>

<?php if(isset(App::getInstance()->sucess)):?>
    <div class="success"><span><?=App::getInstance()->sucess?></span></div>
<?php elseif(isset(App::getInstance()->error)):?>
    <div class="error">
        <span class="error-message"><?=App::getInstance()->error?></span>
    </div>
<?php endif?>
<section class='form'>
    <form action="<?=App::getInstance()->routes->url('User.connect')?>" method="POST" id="connect">
        <h2>connection</h2>
        <?=$form->input('email', 'email', ['type' => 'email'])?>
        <?=$form->input('password','mot de passe',['type'=> "password"])?>
        <button type="submit">connect</button>
    </form>
</section>
