<section class="container-annoncement">
    <?php foreach($annoncements as $annoncement):?>

        <article>
            <a href="index.php?action=annoncement.detail&id=<?=$annoncement->getId()?>">
                <!--<section class="slider">
                    <div class="flexslider">
                        <ul class="slides">
                verifier si l'image existe         -->

                            <?php foreach($annoncement->getImages() as $image):?>

                                <li>
                                    <img src=".././public/<?=$image->getPath().$image->getName()?>">
                                </li>
                            <?php endforeach;?>
                <!--  </ul>
                    </div>
                </section>
-->
                <h3><?=$annoncement->getTitle()?></h3>
                <span><?=$annoncement->getCity().'/'.$annoncement->getZip()?></span>
            </a>
        </article>

    <?php endforeach;?>
</section>
<div class = "pagination">
    <?php if($currentPage > 1):?>
        <a href="index.php?action=<?=$_GET['action']?>&pages=<?=$currentPage - 1?>">&laquo; Page précédent</a>
    <?php endif;?>
    <?php for($i= 1; $i <= $pages; $i++):?>
        <a  <?=($i == $currentPage)?'id="active"':''?>" href="index.php?action=<?=$_GET['action']?>&pages=<?=$i?>"><?=$i?></a>
    <?php endfor;?>
    <?php if($currentPage < $pages):?>
        <a href="index.php?action=<?=$_GET['action']?>&pages=<?=$currentPage + 1?>"> Page suivante &raquo</a>
    <?php endif ?>
</div>