<?php

use App\App;
use \App\Entitys\AnnoncementEntity;
?>
<h1>création</h1>
<form action='<?= App::getInstance()->routes->url('Users.Annoncement.create')?>' method="post" enctype="multipart/form-data">
    <?=$form->input('title','titre',['type'=>'text'])?>
    <?=$form->input('description', 'description', ['type'=> 'textarea'])?>
    <?=$form->input('floor','étage')?>
    <?=$form->input('room', 'piéce')?>
    <?=$form->input('surface','surface')?>
    <?=$form->input('price', 'prix')?>
    <?=$form->option('city', 'ville',AnnoncementEntity::CITYS )?>
    <?=$form->input('images[]','images', ['type'=>'file'])?>
    <?=$form->option('category', 'categorie', AnnoncementEntity::CATEGORYS)?>
    <?=$form->option('type', 'type', AnnoncementEntity::TYPES)?>
    <?=$form->submit()?>
</form>