<?php

use App\App;
use \App\Entitys\AnnoncementEntity;
?>
<section class ='inscrire'>

                <?php foreach($annoncement->getImages() as $image):?>

                    <img src=".././public/<?= $image->getPath() .'/'. $image->getName()?>" alt="logo de luxo">
                        <div>
                            <a href=#><i class="fas fa-edit"></i></a>
                            <a href=#><i class="fas fa-trash"></i></a>
                        </div>

                <?php endforeach;?>

    </section>
    <form action='<?= App::getInstance()->routes->url('Users.Annoncement.edit')?>' method='post' enctype="multipart/form-data">

        <?=$form->input('title','titre',['type'=>'text'])?>
        <?=$form->input('description', 'description', ['type'=> 'textarea'])?>
        <?=$form->input('floor','étage')?>
        <?=$form->input('room', 'piéce')?>
        <?=$form->input('surface','surface')?>
        <?=$form->input('price', 'prix')?>
        <?=$form->option('city', 'ville',AnnoncementEntity::CITYS )?>
        <?=$form->option('category', 'categorie', AnnoncementEntity::CATEGORYS)?>
        <?=$form->option('type', 'type', AnnoncementEntity::TYPES)?>
        <?=$form->submit()?>

    </form>
</section>