<?php use App\App;?>
<section class="container-table">
    <h1>mes annonces</h1>
    <?php if($annoncements): ?>
        <div class="tbl-header">
            <table>
                <thead>
                <tr>
                    <th>titre</th>
                    <th>mise en ligne</th>
                    <th>action</th>
                </tr>

                </thead>
            </table>
        </div>
        <div class="tbl-content">
            <table>
                <tbody>
                    <?php foreach($annoncements as $annoncement):?>
                    <tr>
                        <td><a href="<?=App::getInstance()->routes->url('Annoncement.detail', ['id' => $annoncement->getId()])?>"><?=$annoncement->getTitle()?></a> </td>
                        <td><?=$annoncement->getDateAt()?></td>
                        <td>
                            <a href="<?=App::getInstance()->routes->url('Users.Annoncement.edit', ['id' => $annoncement->getId()])?>">edit</a>
                            <a href ="<?=App::getInstance()->routes->url('Users.Annoncement.deleted', ['id' => $annoncement->getId()])?>">supprimé</a>
                        </td>
                    </tr>
                    <?php endforeach;?>

                </tbody>
            </table>
        </div>
    <?php endif; ?>
    <a class="button" href="<?=App::getInstance()->routes->url('Users.Annoncement.create')?>">Add Annoncement</a>
</section>




