<section class="container-annoncement">
    <?php use App\App;
    foreach($annoncements as $annoncement):?>

            <article>
                <a href="<?=App::getInstance()->routes->url('Annoncement.detail', ['id' => $annoncement->getId()])?>">
              <!-- <section class="slider">
                    <div class="flexslider">
                        <ul class="slides">-->
                        <?php foreach($annoncement->getImages() as $image):?>

                            <li>
                                <img src=".././public/<?=$image->getPath().$image->getName()?>">
                            </li>
                        <?php endforeach;?>
                    <!--   </ul>
                    </div>
                </section>
                -->
                <h3><?=$annoncement->getTitle()?></h3>
                <span><?=$annoncement->getCity()?></span>
                </a>
            </article>

    <?php endforeach;?>
</section>
<div class = "pagination">
    <?php if($currentPage > 1):?>
        <a href="<?=App::getInstance()->routes->url('Annoncement.category',['slug'=>'location'])?>&p=<?=$currentPage - 1?>">&laquo; Page précédent</a>
    <?php endif;?>
    <?php for($i= 1; $i <= $pages; $i++):?>
        <a <?=($i == $currentPage)?'id="active"':''?> href="<?=App::getInstance()->routes->url('Annoncement.category',['slug'=>'location'])?>&p=<?=$i?>"><?=$i?></a>
    <?php endfor;?>
    <?php if($currentPage < $pages):?>
        <a href="<?=App::getInstance()->routes->url('Annoncement.category',['slug'=>'location'])?>&p=<?=$currentPage + 1?>"> Page suivante &raquo</a>
    <?php endif ?>
</div>